This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./DissertacaoPPgSC.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file DissertacaoPPgSC.acn....done (49 entries accepted, 0 rejected).
Sorting entries....done (295 comparisons).
Generating output file DissertacaoPPgSC.acr....done (55 lines written, 0 warnings).
Output written in DissertacaoPPgSC.acr.
Transcript written in DissertacaoPPgSC.alg.
